# Generated by Django 5.1.3 on 2024-11-12 21:00

import apps.accounts.managers.user_manager
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de e-mail')),
                ('document', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='telefone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Pode acessar o painel')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_address', to='core.address', verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['name', '-created_at'],
            },
            managers=[
                ('objects', apps.accounts.managers.user_manager.UserManager()),
            ],
        ),
    ]
