# Generated by Django 5.1.3 on 2024-11-12 21:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=255, verbose_name='rua')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='complemento')),
                ('district', models.CharField(max_length=255, verbose_name='bairro')),
                ('city', models.CharField(max_length=255, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='estado')),
                ('zip_code', models.CharField(max_length=8, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['street'],
            },
        ),
    ]
