# Generated by Django 5.1.3 on 2024-11-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id externo mercadopago'),
        ),
    ]
