# Generated by Django 5.1.3 on 2024-11-13 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('installments', models.IntegerField(default=1, verbose_name='parcelas')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('pix', 'PIX')], max_length=50, verbose_name='Tipo de pagamento')),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do titular')),
                ('card_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Últimos quatro dígitos')),
                ('last_four_digits', models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos quatro dígitos')),
                ('expiration_month', models.CharField(blank=True, max_length=2, null=True, verbose_name='Mês de expiração')),
                ('expiration_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano de expiração')),
                ('security_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Código de segurança')),
                ('issuer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bandeira')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
