# Generated by Django 5.1.3 on 2024-11-12 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('preference_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='id preferência')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('currency', models.CharField(default='BRL', max_length=10, verbose_name='moeda')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantidade')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.user', verbose_name='usuário')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
