# Generated by Django 5.1.3 on 2024-11-12 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('pix', 'PIX')], max_length=50, verbose_name='Tipo de pagamento')),
                ('last_four_digits', models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos quatro dígitos')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provedor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.user', verbose_name='Usuário')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
