# Generated by Django 5.1.3 on 2024-11-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'pagamento', 'verbose_name_plural': 'pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Método de pagamento', 'verbose_name_plural': 'Métodos de pagamento'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Aguardando'), ('preauth', 'Pré Autorizado'), ('confirmed', 'Confirmado'), ('rejected', 'Rejeitado'), ('refunded', 'Estornado'), ('error', 'Erro'), ('input', 'Aguardando Entrada')], default='waiting', max_length=255, null=True, verbose_name='status'),
        ),
    ]
